name: Build and Deploy to GitHub Pages

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build HTML version
        run: ./gradlew html:build

      - name: Upload HTML build artifact
        uses: actions/upload-artifact@v3
        with:
          name: gdxvania-html-build
          path: ./html/webapp/*

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html/webapp
