name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build HTML version
        run: ./gradlew html:dist

      - name: Upload HTML build artifact
        uses: actions/upload-artifact@v4
        with:
          name: gdxvania-html-build
          path: ./html/build/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download HTML build artifact
        uses: actions/download-artifact@v4
        with:
          name: gdxvania-html-build
          path: ./

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
